apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: my-cute-postgres-cluster
  namespace: services
spec:
  postgresVersion: 17

  instances:
  - name: instance1
    replicas: 1
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

    resources:
      requests:
        cpu: 1000m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 2Gi

  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          pg_hba:
            - "host all all all md5"

  users:
  - name: trino
    databases:
    - trino-catalog
    options: "CREATEDB"
  - name: zitadel
    databases:
    - zitadel
    options: "CREATEDB"
