# Values for the traefik-wrapper chart

# Values passed to the 'traefik' subchart (dependency)
traefik:
  # Enable dashboard access (consider security implications for production)
  ingressRoute:
    dashboard:
      enabled: true
      # Use the default entrypoint for the dashboard
      entryPoints:
      - websecure
      # Define the matching rule for the dashboard route
      matchRule: Host(`traefik.localhost`)
  ports:
    web:
      transport:
        respondingTimeouts:
          readTimeout: 3600
          writeTimeout: 3600
          idleTimeout: 3600
        keepAliveMaxTime: 3600
        keepAliveMaxRequests: 1000

  logs:
    general:
      level: DEBUG
    access:
      enabled: true

  # Enable Kubernetes providers
  providers:
    kubernetesCRD:
      enabled: true # Enable CRD provider (for IngressRoute, ServersTransport, etc.)
    kubernetesIngress:
      enabled: true
