# Values for the traefik-wrapper chart

# Values passed to the 'traefik' subchart (dependency)
traefik:
  # Enable dashboard access (consider security implications for production)
  ingressRoute:
    dashboard:
      enabled: true
      # Use the default entrypoint for the dashboard
      entryPoints:
        - websecure
      # Define the matching rule for the dashboard route
      matchRule: Host(`traefik.exoscale.robberthofman.com`)

  # Enable Kubernetes providers
  providers:
    kubernetesCRD:
      enabled: true # Enable CRD provider (for IngressRoute, ServersTransport, etc.)
    kubernetesIngress:
      enabled: true

  ports:
    web:
      port: 8000
      protocol: TCP
      exposedPort: 80
    websecure:
      port: 8443
      protocol: TCP
      exposedPort: 443
      tls:
        enabled: true

  # add some middleware to serve the acme challenge over HTTP
  middleware:
    skip-acme-redirect:
      redirectRegex:
        regex: "^/\\.well-known/acme-challenge/(.*)"
        replacement: "/.well-known/acme-challenge/$1"
        permanent: false

  routers:
    acme-challenge:
      entryPoints:
        - web
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      service: api@internal
      priority: 100
      middlewares:
        - skip-acme-redirect@internal


  entryPoints:
    web:
      address: ":80"
      # Use middleware for HTTPS redirect
      http:
        redirections:
          entrypoint:
            to: websecure
            scheme: https
            permanent: true
    websecure:
      address: ":443"

  # Configure Let's Encrypt ACME
  certificatesResolvers:
    letsencrypt:
      acme:
        # ACME CA server to use
        caServer: https://acme-v02.api.letsencrypt.org/directory
        # Email address used for registration
        email: robbert.hofman@dataminded.com
        # File or key used for certificates storage
        storage: /acme/acme.json
        # HTTP challenge
        httpChallenge:
          entryPoint: web

  # Persistence for ACME certificates
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    path: /acme
    annotations: {}
      # Additional configuration to ensure ACME works

  additionalArguments:
    - "--log.level=DEBUG"
