# Custom values for the Trino Helm chart
# Values placed under the 'trino:' key will be passed to the subchart.
trino:
  additionalConfigProperties:
  - http-server.process-forwarded=true
  envFrom:
  - secretRef:
      name: s3-credentials
    prefix: S3_
  - secretRef:
      name: pg-credentials
    prefix: PG_
  catalogs:
    iceberg: |
      connector.name=iceberg
      iceberg.catalog.type=jdbc
      iceberg.jdbc-catalog.catalog-name=catalog
      iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
      iceberg.jdbc-catalog.connection-url=jdbc:postgresql://${ENV:PG_HOST}:${ENV:PG_PORT}/catalog
      iceberg.jdbc-catalog.connection-user=${ENV:PG_USERNAME}
      iceberg.jdbc-catalog.connection-password=${ENV:PG_PASSWORD}
      iceberg.jdbc-catalog.default-warehouse-dir=s3://dp-stack-tf-os
      fs.native-s3.enabled=true
      s3.endpoint=${ENV:S3_ENDPOINT}
      s3.region=${ENV:S3_REGION}
      s3.aws-access-key=${ENV:S3_ACCESS_KEY_ID}
      s3.aws-secret-key=${ENV:S3_SECRET_ACCESS_KEY}
  auth:
    passwordAuth: "admin:$2b$08$mJ4nVo8R63bcmJlBNxOsreqLaQF3ajVGAgvHZ28QAOOJ23VFgYTxG"

  # Configure ingress for Trino
  ingress:
    enabled: true
    annotations:
      # Use Traefik's websecure entrypoint for HTTPS
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS termination at the router (Traefik handles certs)
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
    - host: trino.cloudfleet.platform.5ha.re
      paths:
      - path: /
        pathType: Prefix
