# Custom values for the Trino Helm chart
# Values placed under the 'trino:' key will be passed to the subchart.
trino:
  envFrom:
    - secretRef:
        name: s3-credentials
      prefix: S3_
    - secretRef:
        name: pg-credentials
      prefix: PG_
  catalogs:
    iceberg: |
      connector.name=iceberg
      iceberg.catalog.type=rest
      iceberg.rest-catalog.uri=http://lakekeeper.services.svc.cluster.local:8181/catalog
      iceberg.rest-catalog.warehouse=dataminded
      fs.native-s3.enabled=true
      s3.endpoint=${ENV:S3_ENDPOINT}
      s3.region=${ENV:S3_REGION}
      s3.aws-access-key=${ENV:S3_ACCESS_KEY_ID}
      s3.aws-secret-key=${ENV:S3_SECRET_ACCESS_KEY}
      iceberg.rest-catalog.security=NONE
      iceberg.rest-catalog.vended-credentials-enabled=true
      fs.native-s3.enabled=true
      s3.endpoint=${ENV:S3_ENDPOINT}
      s3.region=${ENV:S3_REGION}
      s3.aws-access-key=${ENV:S3_ACCESS_KEY_ID}
      s3.aws-secret-key=${ENV:S3_SECRET_ACCESS_KEY}

  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts: 
      - host: trino.upcloud.playground.dataminded.cloud
        paths:
          - path: /
            pathType: Prefix