apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crunchy-postgres-operator
  namespace: operators
  # Add finalizer to ensure that Helm release is deleted before the app
  finalizers:
  - argocd.argoproj.io/resources-finalizer # Use domain-qualified finalizer
spec:
  project: default
  source:
    # Source is the Git repository containing this Application manifest and the wrapper chart
    repoURL: https://github.com/datamindedbe/playground-data-platform-stack.git
    path: argo/apps/430-crunchy-postgres-operator # Path to the wrapper chart directory within the Git repo
    targetRevision: cloudfleet # Or your specific branch/tag

    # Helm configuration for the wrapper chart
    helm:
      # releaseName is optional here, defaults based on app name
      releaseName: crunchy-postgres-operator
      # Values file is implicitly values.yaml within the source path
      # valueFiles: # Not needed if using default values.yaml
      #  - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator # Deploy Crunchy Postgres Operator into its own namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Ensure the postgres-operator namespace is created 
