apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zitadel-cert
spec:
  secretName: zitadel-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - zitadel.cloudfleet.platform.5ha.re
