apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
spec:
  secretName: vault-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - vault.ovh.playground.dataminded.cloud
