expose:
  type: ingress
  tls:
    enabled: false
  ingress:
    hosts:
      core: harbor.upcloud.playground.dataminded.cloud
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"

externalURL: http://harbor.upcloud.playground.dataminded.cloud

harborAdminPassword: "Harbor12345"  # changeme