# Default values for zitadel.
zitadel:
  zitadel:
    masterkey: x123456789012345678901234567891y
    configmapConfig:
      # ExternalSecure: false
      ExternalDomain: "zitadel.cloudfleet.platform.5ha.re"
      # TLS:
      #   Enabled: false # TLS termination at ingress level
      # ExternalPort: 443
      # Use External Secret with template that combines:
      # - PostgreSQL credentials from k8s-services ClusterSecretStore (Crunchy-generated secret)

      # - SMTP credentials from vault-backend ClusterSecretStore
      # configSecretName: zitadel-config

      # configSecretKey: config.yaml
      # dbSslCaCrtSecret: pg-certificate
    envSecretName: zitadel-envs
  ingress:
    enabled: true
    className: traefik
    annotations:
      # Use Traefik's websecure entrypoint for HTTPS
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS termination at the router (Traefik handles certs)
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
    - host: zitadel.cloudfleet.platform.5ha.re
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - zitadel.cloudfleet.platform.5ha.re
      secretName: zitadel-tls
