# Default values for zitadel.
zitadel:
  zitadel:
    masterkey: x123456789012345678901234567891y
    configmapConfig:
      ExternalSecure: false
      ExternalDomain: localhost
      TLS:
        Enabled: false
    configSecretName: zitadel-credentials
    configSecretKey: config.yaml
    dbSslCaCrtSecret: pg-certificate
      