# Default values for zitadel.
zitadel:
  zitadel:
    masterkey: x123456789012345678901234567891y
    configmapConfig:
      ExternalSecure: false
      ExternalDomain: 127.0.0.1.sslip.io
      TLS:
        Enabled: false
      Database:
        Postgres:
          MaxOpenConns: 20
          MaxIdleConns: 10
          MaxConnLifetime: 30m
          MaxConnIdleTime: 5m
          User:
            Username: postgres
            SSL:
              Mode: disable
    configSecretName: zitadel-credentials
    configSecretKey: config.yaml
      