# Default values for zitadel.
zitadel:
  zitadel:
    masterkey: x123456789012345678901234567891y
    configmapConfig:
      ExternalSecure: false
      ExternalDomain: localhost
      TLS:
        Enabled: false
      FirstInstance:
        Org:
          Human:
            Username: "admin"
            Password: "SecureP@ssw0rd!"
            FirstName: "Default"
            LastName: "Admin"
            Email:
              Address: "admin@dataminded.com"
              Verified: true
    configSecretName: zitadel-credentials
    configSecretKey: config.yaml
    dbSslCaCrtSecret: pg-certificate
    ingress:
      enabled: true
      className: traefik
      hosts: 
        - host: zitadel.exoscale.robberthofman.com

