# Default values for portal.
data-product-portal:
  oidc:
    enabled: true
    authority: https://zitadel.exoscale.robberthofman.com
    redirect_uri: https://portal.exoscale.robberthofman.com/
  smtp:
    host: smtp.tem.scaleway.com
    port: '!!string 587'
  from_mail_address: portal@exoscale.robberthofman.com
  ingress:
    enabled: true
    className: traefik
    annotations:
      # Enable TLS with Let's Encrypt
      traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
    hosts: 
      - host: portal.exoscale.robberthofman.com
        paths:
        - path: /api
          pathType: Prefix
          name: data-product-portal
          number: 5050
        - path: /
          pathType: Prefix
          name: frontend
          number: 8080
  host: https://portal.exoscale.robberthofman.com
  api_key: 
    enabled: false
  namespace_max_length: '!!string 30'
  image:
    tag: 'c121704'
  frontendimage:
    tag: 'c121704'
  global:
    postgresql:
      auth:
        password: admin1234
        database: data-product-portal
        port: "!!string 5432"
        server: portal-postgresql
        username: postgres
  postgres_enabled: true