apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trino-cert
spec:
  secretName: trino-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - trino.cloudfleet.platform.5ha.re 