apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-credentials
spec:
  refreshInterval: 300s # Refresh every 5 minutes
  secretStoreRef:
    name: k8s-services
    kind: ClusterSecretStore
  data:
   - secretKey: PG_HOST # Key in the Kubernetes Secret
     remoteRef:
       key: my-cute-postgres-cluster-pguser-trino
       property: host  # Property to extract from the Vault secret
   - secretKey: PG_PORT # Key in the Kubernetes Secret
     remoteRef:
       key: my-cute-postgres-cluster-pguser-trino
       property: port  # Property to extract from the Vault secret
   - secretKey: PG_USERNAME # Key in the Kubernetes Secret
     remoteRef:
       key: my-cute-postgres-cluster-pguser-trino
       property: user  # Property to extract from the Vault secret
   - secretKey: PG_PASSWORD # Key in the Kubernetes Secret
     remoteRef:
       key: my-cute-postgres-cluster-pguser-trino
       property: password  # Property to extract from the Vault secret
