apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
spec:
  refreshInterval: 300s # Refresh every 5 minutes
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
   - secretKey: ENDPOINT # Key in the Kubernetes Secret
     remoteRef:
       key: platform/s3-credentials  # Path in Vault
       property: ENDPOINT  # Property to extract from the Vault secret
   - secretKey: ACCESS_KEY_ID # Key in the Kubernetes Secret
     remoteRef:
       key: platform/s3-credentials  # Path in Vault
       property: ACCESS_KEY_ID  # Property to extract from the Vault secret
   - secretKey: REGION # Key in the Kubernetes Secret
     remoteRef:
       key: platform/s3-credentials  # Path in Vault
       property: REGION  # Property to extract from the Vault secret
   - secretKey: SECRET_ACCESS_KEY # Key in the Kubernetes Secret
     remoteRef:
       key: platform/s3-credentials  # Path in Vault
       property: SECRET_ACCESS_KEY  # Property to extract from the Vault secret

