apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hcloud-token
  namespace: kube-system
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: hcloud
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: cloud/hetzner
      property: roottoken 