apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zot-cert
spec:
  secretName: zot-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - zot.cloudfleet.platform.5ha.re
