apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot-config
spec:
  refreshInterval: 300s # Refresh every 5 minutes
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: zot-config
    template:
      engineVersion: v2
            #"distSpecVersion": "1.1.1",
      data:
        config.json: |
          {
            "storage": {
              "rootDirectory": "/var/lib/registry",
              "dedupe": false,
              "storageDriver": {
                "name": "s3",
                "rootdirectory": "/platform/zot",
                "region": "{{`{{ .region }}`}}",
                "regionendpoint": "{{`{{ .endpoint }}`}}",
                "bucket": "inno-days-bucket",
                "accesskey": "{{`{{ .access_key_id }}`}}",
                "secretkey": "{{`{{ .secret_access_key }}`}}",
                "secure": true,
                "skipverify": false
              }
            },
            "http": {
              "address": "0.0.0.0",
              "port": "5000",
              "compat": ["docker2s2"]
            },
            "log": {
              "level": "debug",
              "output": "/dev/stdout",
              "audit": "/dev/stdout"
            },
            "extensions": {
                "search": {
                    "enable": true
                },
                "ui": {
                    "enable": true
                }
            }
          }
  data:
  - secretKey: access_key_id
    remoteRef:
      key: platform/s3-credentials
      property: ACCESS_KEY_ID
  - secretKey: secret_access_key
    remoteRef:
      key: platform/s3-credentials
      property: SECRET_ACCESS_KEY
  - secretKey: region
    remoteRef:
      key: platform/s3-credentials
      property: REGION
  - secretKey: endpoint
    remoteRef:
      key: platform/s3-credentials
      property: ENDPOINT
