apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-product-portal.frontendfullname" . }}
  labels:
    {{- include "data-product-portal.frontendlabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontendservice.type }}
  ports:
    - port: {{ .Values.frontendservice.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "data-product-portal.frontendselectorLabels" . | nindent 4 }}
