apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airflow-cert
spec:
  secretName: airflow-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - airflow.cloudfleet.platform.5ha.re 