# Custom values for the zot Helm chart
# Values placed under the 'zot:' key will be passed to the subchart.
zot:
  image:
    # use zot multi-arch image
    repository: ghcr.io/project-zot/zot
    tag: "v2.1.4"

  # Ensure zot runs on AMD64 nodes (or use ARM64 image instead)
  # nodeSelector:
  #   kubernetes.io/arch: amd64

  # Mount only the config.json key from the secret to the specific file
  extraVolumes:
  - name: zot-config-volume
    secret:
      secretName: zot-config
      items:
      - key: config.json
        path: config.json

  extraVolumeMounts:
  - name: zot-config-volume
    mountPath: /etc/zot/config.json
    subPath: config.json
    readOnly: true
  # Configure ingress for zot
  ingress:
    enabled: true
    className: traefik
    annotations:
      # Use Traefik's websecure entrypoint for HTTPS
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # Enable TLS termination at the router (Traefik handles certs)
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
    - host: zot.cloudfleet.platform.5ha.re
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - zot.cloudfleet.platform.5ha.re
      secretName: zot-tls

  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
