apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airflow-cert
spec:
  secretName: airflow-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - airflow.ovh.playground.dataminded.cloud